#!/usr/bin/env python3
"""Build js/history25.js from data/history/*.json.

The FPL API wipes every player's aggregate stats when it flips to the new
season (~mid-July). The archive under data/history/ was taken before the
wipe; this script bakes it into a script file the app loads alongside
data.js, keyed by the immutable FPL player *code* (stable across seasons,
unlike the per-season element id).

Also bakes the league's 25/26 record (matches, honours) for the Record Book.

Run once after updating data/history/, commit the output.
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
hist = root / 'data' / 'history'

players = json.load(open(hist / 'players25.json'))
league = json.load(open(hist / 'epl25.json'))

by_code = {}
for p in players['players']:
    by_code[p['code']] = {
        'pts': p['pts'],
        'ppg': p['ppg'],
        'g': p['g'],
        'a': p['a'],
        'cs': p['cs'],
        'xgi': round((p.get('xg') or 0) + (p.get('xa') or 0), 1),
        'mp': p['mp'],
        'club': p['club'],
    }

season_block = {
    'season': league['season'],
    'managers': league['managers'],
    'matches': league['matches'],
    'honours': league['honours'],
}

out = (
    '// Generated by scripts/build_history.py — do not edit by hand.\n'
    '// Last season (2025/26) player stats keyed by immutable FPL code,\n'
    '// plus the league record for the Record Book.\n'
    'const LAST_SEASON = ' + json.dumps(
        {'season': players['season'], 'byCode': by_code},
        ensure_ascii=False, separators=(',', ':')) + ';\n'
    'const LEAGUE_HISTORY = [' + json.dumps(
        season_block, ensure_ascii=False, separators=(',', ':')) + '];\n'
)

(root / 'js' / 'history25.js').write_text(out, encoding='utf-8')
print(f'js/history25.js written — {len(by_code)} players, '
      f'{len(season_block["matches"])} matches')
