#!/usr/bin/env python3
"""Fetch FPL data and regenerate the site's data files.

Outputs:
  js/data.js         TEAMS / PLAYERS / GAMEWEEKS (loaded synchronously by the app)
  data/stats.json    raw per-player stats per gameweek (fetched at runtime)
  data/fixtures.json PL fixture list with scores

Run by the GitHub Action on a schedule; safe to run locally any time.
"""
import json
import time
import urllib.request
from pathlib import Path

BASE = 'https://fantasy.premierleague.com/api'
ROOT = Path(__file__).resolve().parent.parent
POS = {1: 'GK', 2: 'DF', 3: 'MF', 4: 'FW'}


def get(url, retries=3):
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'the-league/1.0'})
            with urllib.request.urlopen(req, timeout=30) as r:
                return json.load(r)
        except Exception:
            if i == retries - 1:
                raise
            time.sleep(2 * (i + 1))


def main():
    boot = get(f'{BASE}/bootstrap-static/')

    teams = [{
        'id': t['id'],
        'name': t['name'],
        'short': t['short_name'],
        'code': t['code'],
        # blended FPL strength rating, used for fixture-ease in the weekly preview
        'str': round((t['strength_overall_home'] + t['strength_overall_away']) / 2),
    } for t in boot['teams']]
    team_name = {t['id']: t['name'] for t in teams}
    team_short = {t['id']: t['short_name'] for t in boot['teams']}

    players = []
    for e in boot['elements']:
        if e['element_type'] not in POS:  # skip assistant-manager elements
            continue
        pts = e.get('total_points') or 0
        players.append({
            'id': e['id'],
            'name': e['web_name'],
            'full': f"{e['first_name']} {e['second_name']}".strip(),
            'team': team_name[e['team']],
            'club': team_short[e['team']],
            'pos': POS[e['element_type']],
            'code': e['code'],
            'status': e['status'],           # a/d/i/s/u
            'news': e.get('news') or '',
            # when the news line last changed + chance of playing, for the Treatment Room
            'newsAdded': e.get('news_added') or '',
            'chance': e.get('chance_of_playing_next_round'),
            'price': e['now_cost'] / 10,
            'pts': pts,
            # draft-room guide: points if the season has any, else price as proxy
            'rating': pts if pts > 0 else round(e['now_cost'] / 10),
            # FPL's own expected points for the next gameweek — feeds projections
            'xp': float(e.get('ep_next') or 0),
            'ppg': float(e.get('points_per_game') or 0),
            # season aggregates for the pool table and player cards
            'mp': e.get('minutes') or 0,
            'g': e.get('goals_scored') or 0,
            'a': e.get('assists') or 0,
            'cs': e.get('clean_sheets') or 0,
            'xg': float(e.get('expected_goals') or 0),
            'xa': float(e.get('expected_assists') or 0),
        })

    events = boot['events']
    gameweeks = []
    for i, ev in enumerate(events):
        nxt = events[i + 1]['deadline_time'] if i + 1 < len(events) else None
        gameweeks.append({
            'n': ev['id'],
            'label': ev['name'],
            'deadline': ev['deadline_time'],
            'to': nxt or ev['deadline_time'][:10] + 'T23:59:59Z',
            'finished': ev['finished'],
        })
    # last GW has no successor: give its window a week after the deadline
    if gameweeks:
        import datetime as dt
        d = dt.datetime.fromisoformat(gameweeks[-1]['deadline'].replace('Z', '+00:00'))
        gameweeks[-1]['to'] = (d + dt.timedelta(days=7)).strftime('%Y-%m-%dT%H:%M:%SZ')

    header = f"// Generated by scripts/fetch_fpl.py — do not edit by hand.\n// Source: official FPL API. Season: {boot['events'][0]['deadline_time'][:4]}/{int(boot['events'][0]['deadline_time'][:4]) % 100 + 1}.\n"
    data_js = (
        header
        + 'const TEAMS = ' + json.dumps(teams, ensure_ascii=False) + ';\n'
        + 'const PLAYERS = ' + json.dumps(players, ensure_ascii=False) + ';\n'
        + 'const GAMEWEEKS_RAW = ' + json.dumps(gameweeks, ensure_ascii=False) + ';\n'
    )
    (ROOT / 'js' / 'data.js').write_text(data_js, encoding='utf-8')

    # pure-JSON mirror of data.js for the server (Cloud Functions parse this as
    # data — they never execute fetched code)
    (ROOT / 'data' / 'data.json').write_text(json.dumps({
        'generated': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'teams': teams,
        'players': players,
        'gameweeks': gameweeks,
    }, ensure_ascii=False), encoding='utf-8')

    # fixtures
    fx = get(f'{BASE}/fixtures/')
    fixtures = [{
        'id': f['id'],
        'gw': f.get('event'),
        'date': f.get('kickoff_time'),
        'home': team_name.get(f['team_h'], '?'),
        'away': team_name.get(f['team_a'], '?'),
        'hs': f.get('team_h_score'),
        'as': f.get('team_a_score'),
        'started': bool(f.get('started')),
        'finished': bool(f.get('finished')),
        'minutes': f.get('minutes') or 0,
    } for f in fx]
    (ROOT / 'data' / 'fixtures.json').write_text(
        json.dumps(fixtures, ensure_ascii=False), encoding='utf-8')

    # per-GW raw stats — only GWs that have started
    current = next((ev['id'] for ev in events if ev['is_current']), None)
    gws = {}
    for ev in events:
        if not (ev['finished'] or ev['is_current'] or (ev.get('data_checked'))):
            continue
        live = get(f'{BASE}/event/{ev["id"]}/live/')
        # FPL identifier -> our short key, for reading the per-fixture `explain`
        EXPLAIN_MAP = {
            'minutes': 'min', 'goals_scored': 'g', 'assists': 'a',
            'clean_sheets': 'cs', 'goals_conceded': 'gc', 'own_goals': 'og',
            'penalties_saved': 'ps', 'penalties_missed': 'pm',
            'yellow_cards': 'yc', 'red_cards': 'rc', 'saves': 'sv',
        }
        stats = {}
        for el in live['elements']:
            s = el['stats']
            if s['minutes'] == 0 and not any([s['yellow_cards'], s['red_cards']]):
                continue
            # st = number of STARTS in the gameweek (feeds the start-2 / sub-1
            # appearance rule; can be 2+ in a double gameweek)
            started = s.get('starts', 1 if s['minutes'] >= 60 else 0)
            row = {
                'min': s['minutes'],
                'st': int(started),
                'sub': 1 if (s['minutes'] > 0 and not started) else 0,
                'g': s['goals_scored'],
                'a': s['assists'],
                'cs': s['clean_sheets'],
                'gc': s['goals_conceded'],
                'og': s['own_goals'],
                'ps': s['penalties_saved'],
                'pm': s['penalties_missed'],
                'yc': s['yellow_cards'],
                'rc': s['red_cards'],
                'sv': s['saves'],
            }
            # double gameweek: the aggregate above mis-scores per-match rules
            # (appearance, goals-conceded per 2, saves per 3). Store each fixture
            # separately so the app can score match-by-match and sum. Any stat
            # absent from a fixture's explain scored 0 that match, so 0 is right.
            explain = el.get('explain') or []
            if len(explain) >= 2:
                fx = []
                for ex in explain:
                    fs = {'min': 0, 'g': 0, 'a': 0, 'cs': 0, 'gc': 0, 'og': 0,
                          'ps': 0, 'pm': 0, 'yc': 0, 'rc': 0, 'sv': 0}
                    for st in ex.get('stats', []):
                        k = EXPLAIN_MAP.get(st['identifier'])
                        if k:
                            fs[k] = st['value']
                    fx.append(fs)
                row['fx'] = fx
            stats[el['id']] = row
        gws[str(ev['id'])] = {'finished': ev['finished'], 'stats': stats}

    (ROOT / 'data' / 'stats.json').write_text(json.dumps({
        'generated': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'currentGw': current,
        'gws': gws,
    }, ensure_ascii=False), encoding='utf-8')

    print(f'ok: {len(players)} players, {len(teams)} teams, '
          f'{len(gws)} gameweeks with stats, {len(fixtures)} fixtures')


if __name__ == '__main__':
    main()
